use num_enum::{TryFromPrimitive, IntoPrimitive};

#[derive(Debug, Eq, PartialEq, Copy, Clone, Hash, TryFromPrimitive, IntoPrimitive)]
#[repr(u8)]
pub enum KangXi {
    One = 1,
    Line,
    Dot,
    Slash,
    Second,
    Hook,
    Two,
    Lid,
    Man,
    Son,
    Enter,
    Eight,
    Wide,
    ClothCover,
    Ice,
    Table,
    Receptacle,
    Knife,
    Power,
    Wrap,
    Spoon,
    Box,
    Hiding,
    Ten,
    Divination,
    Seal,
    Cliff,
    Private,
    Again,
    Mouth,
    Enclosure,
    Earth,
    Scholar,
    Go,
    GoSlowly,
    Evening,
    Big,
    Woman,
    Child,
    Roof,
    Inch,
    Small,
    Lame,
    Corpse,
    Sprout,
    Mountain,
    River,
    Work,
    Oneself,
    Turban,
    Dry,
    ShortThread,
    DottedCliff,
    LongStride,
    Arch,
    Shoot,
    Bow,
    Snout,
    Bristle,
    Step,
    Heart,
    Halberd,
    Door,
    Hand,
    Branch,
    Rap,
    Script,
    Dipper,
    Axe,
    Square,
    Not,
    Sun,
    Say,
    Moon,
    Tree,
    Lack,
    Stop,
    Death,
    Weapon,
    DoNot,
    Compare,
    Fur,
    Clan,
    Steam,
    Water,
    Fire,
    Claw,
    Father,
    Trigrams,
    SplitWood,
    Slice,
    Fang,
    Cow,
    Dog,
    Profound,
    Jade,
    Melon,
    Tile,
    Sweet,
    Life,
    Use,
    Field,
    BoltOfCloth,
    Sickness,
    Footsteps,
    White,
    Skin,
    Dish,
    Eye,
    Spear,
    Arrow,
    Stone,
    Spirit,
    Track,
    Grain,
    Cave,
    Stand,
    Bamboo,
    Rice,
    Silk,
    Jar,
    Net,
    Sheep,
    Feather,
    Old,
    And,
    Plow,
    Ear,
    Brush,
    Meat,
    Minister,
    OnesSelf,
    Arrive,
    Mortar,
    Tongue,
    Oppose,
    Boat,
    Stopping,
    Color,
    Grass,
    Tiger,
    Insect,
    Blood,
    WalkEnclosure,
    Clothes,
    Cover,
    See,
    Horn,
    Speech,
    Valley,
    Bean,
    Pig,
    Badger,
    Shell,
    Red,
    Run,
    Foot,
    Body,
    Cart,
    Bitter,
    Morning,
    Walk,
    City,
    Wine,
    Distinguish,
    Village,
    Gold,
    Long,
    Gate,
    Mound,
    Slave,
    ShortTailedBird,
    Rain,
    Blue,
    Wrong,
    Face,
    Leather,
    TannedLeather,
    Leek,
    Sound,
    Leaf,
    Wind,
    Fly,
    Eat,
    Head,
    Fragrant,
    Horse,
    Bone,
    Tall,
    Hair,
    Fight,
    SacrificialWine,
    Cauldron,
    Ghost,
    Fish,
    Bird,
    Salt,
    Deer,
    Wheat,
    Hemp,
    Yellow,
    Millet,
    Black,
    Embroidery,
    Frog,
    Tripod,
    Drum,
    Rat,
    Nose,
    Even,
    Tooth,
    Dragon,
    Turtle,
    Flute,
}

/*
*/

impl Into<&'static str> for KangXi {
    fn into(self) -> &'static str {
        use KangXi::*;
        match self {
            One => "一",
            Line => "丨",
            Dot => "丶",
            Slash => "丿",
            Second => "乙",
            Hook => "亅",
            Two => "二",
            Lid => "亠",
            Man => "人",
            Son => "儿",
            Enter => "入",
            Eight => "八",
            Wide => "冂",
            ClothCover => "冖",
            Ice => "冫",
            Table => "几",
            Receptacle => "凵",
            Knife => "刀",
            Power => "力",
            Wrap => "勹",
            Spoon => "匕",
            Box => "匚",
            Hiding => "匸",
            Ten => "十",
            Divination => "卜",
            Seal => "卩",
            Cliff => "厂",
            Private => "厶",
            Again => "又",
            Mouth => "口",
            Enclosure => "囗",
            Earth => "土",
            Scholar => "士",
            Go => "夂",
            GoSlowly => "夊",
            Evening => "夕",
            Big => "大",
            Woman => "女",
            Child => "子",
            Roof => "宀",
            Inch => "寸",
            Small => "小",
            Lame => "尢",
            Corpse => "尸",
            Sprout => "屮",
            Mountain => "山",
            River => "巛",
            Work => "工",
            Oneself => "己",
            Turban => "巾",
            Dry => "干",
            ShortThread => "幺",
            DottedCliff => "广",
            LongStride => "廴",
            Arch => "廾",
            Shoot => "弋",
            Bow => "弓",
            Snout => "彐",
            Bristle => "彡",
            Step => "彳",
            Heart => "心",
            Halberd => "戈",
            Door => "戶",
            Hand => "手",
            Branch => "支",
            Rap => "攴",
            Script => "文",
            Dipper => "斗",
            Axe => "斤",
            Square => "方",
            Not => "无",
            Sun => "日",
            Say => "曰",
            Moon => "月",
            Tree => "木",
            Lack => "欠",
            Stop => "止",
            Death => "歹",
            Weapon => "殳",
            DoNot => "毋",
            Compare => "比",
            Fur => "毛",
            Clan => "氏",
            Steam => "气",
            Water => "水",
            Fire => "火",
            Claw => "爪",
            Father => "父",
            Trigrams => "爻",
            SplitWood => "爿",
            Slice => "片",
            Fang => "牙",
            Cow => "牛",
            Dog => "犬",
            Profound => "玄",
            Jade => "玉",
            Melon => "瓜",
            Tile => "瓦",
            Sweet => "甘",
            Life => "生",
            Use => "用",
            Field => "田",
            BoltOfCloth => "疋",
            Sickness => "疒",
            Footsteps => "癶",
            White => "白",
            Skin => "皮",
            Dish => "皿",
            Eye => "目",
            Spear => "矛",
            Arrow => "矢",
            Stone => "石",
            Spirit => "示",
            Track => "禸",
            Grain => "禾",
            Cave => "穴",
            Stand => "立",
            Bamboo => "竹",
            Rice => "米",
            Silk => "糸",
            Jar => "缶",
            Net => "网",
            Sheep => "羊",
            Feather => "羽",
            Old => "老",
            And => "而",
            Plow => "耒",
            Ear => "耳",
            Brush => "聿",
            Meat => "肉",
            Minister => "臣",
            OnesSelf => "自",
            Arrive => "至",
            Mortar => "臼",
            Tongue => "舌",
            Oppose => "舛",
            Boat => "舟",
            Stopping => "艮",
            Color => "色",
            Grass => "艸",
            Tiger => "虍",
            Insect => "虫",
            Blood => "血",
            WalkEnclosure => "行",
            Clothes => "衣",
            Cover => "襾",
            See => "見",
            Horn => "角",
            Speech => "言",
            Valley => "谷",
            Bean => "豆",
            Pig => "豕",
            Badger => "豸",
            Shell => "貝",
            Red => "赤",
            Run => "走",
            Foot => "足",
            Body => "身",
            Cart => "車",
            Bitter => "辛",
            Morning => "辰",
            Walk => "辵",
            City => "邑",
            Wine => "酉",
            Distinguish => "釆",
            Village => "里",
            Gold => "金",
            Long => "長",
            Gate => "門",
            Mound => "阜",
            Slave => "隶",
            ShortTailedBird => "隹",
            Rain => "雨",
            Blue => "靑",
            Wrong => "非",
            Face => "面",
            Leather => "革",
            TannedLeather => "韋",
            Leek => "韭",
            Sound => "音",
            Leaf => "頁",
            Wind => "風",
            Fly => "飛",
            Eat => "食",
            Head => "首",
            Fragrant => "香",
            Horse => "馬",
            Bone => "骨",
            Tall => "高",
            Hair => "髟",
            Fight => "鬥",
            SacrificialWine => "鬯",
            Cauldron => "鬲",
            Ghost => "鬼",
            Fish => "魚",
            Bird => "鳥",
            Salt => "鹵",
            Deer => "鹿",
            Wheat => "麥",
            Hemp => "麻",
            Yellow => "黃",
            Millet => "黍",
            Black => "黑",
            Embroidery => "黹",
            Frog => "黽",
            Tripod => "鼎",
            Drum => "鼓",
            Rat => "鼠",
            Nose => "鼻",
            Even => "齊",
            Tooth => "齒",
            Dragon => "龍",
            Turtle => "龜",
            Flute => "龠",
        }
    }
}

pub struct RadicalGlyph {
    pub primary: &'static str,
    pub secondary: &[&'static str],
}

impl From<&'static str> for RadicalGlyph {
    fn from(s: &str) -> Self {
        Self {
            primary: s,
            secondary: &[],
        }
    }
}