use num_enum::{IntoPrimitive, TryFromPrimitive};
use serde::{Serialize, Deserialize};

#[derive(
    Debug, Eq, PartialEq, Copy, Clone, Hash, TryFromPrimitive, IntoPrimitive, PartialOrd, Ord, Serialize, Deserialize,
)]
#[repr(u8)]
pub enum KangXi {
    One = 1,
    Line,
    Dot,
    Slash,
    Second,
    Hook,
    Two,
    Lid,
    Man,
    Son,
    Enter,
    Eight,
    Wide,
    ClothCover,
    Ice,
    Table,
    Receptacle,
    Knife,
    Power,
    Wrap,
    Spoon,
    Box,
    Hiding,
    Ten,
    Divination,
    Seal,
    Cliff,
    Private,
    Again,
    Mouth,
    Enclosure,
    Earth,
    Scholar,
    Go,
    GoSlowly,
    Evening,
    Big,
    Woman,
    Child,
    Roof,
    Inch,
    Small,
    Lame,
    Corpse,
    Sprout,
    Mountain,
    River,
    Work,
    Oneself,
    Turban,
    Dry,
    ShortThread,
    DottedCliff,
    LongStride,
    Arch,
    Shoot,
    Bow,
    Snout,
    Bristle,
    Step,
    Heart,
    Halberd,
    Door,
    Hand,
    Branch,
    Rap,
    Script,
    Dipper,
    Axe,
    Square,
    Not,
    Sun,
    Say,
    Moon,
    Tree,
    Lack,
    Stop,
    Death,
    Weapon,
    DoNot,
    Compare,
    Fur,
    Clan,
    Steam,
    Water,
    Fire,
    Claw,
    Father,
    Trigrams,
    SplitWood,
    Slice,
    Fang,
    Cow,
    Dog,
    Profound,
    Jade,
    Melon,
    Tile,
    Sweet,
    Life,
    Use,
    Field,
    BoltOfCloth,
    Sickness,
    Footsteps,
    White,
    Skin,
    Dish,
    Eye,
    Spear,
    Arrow,
    Stone,
    Spirit,
    Track,
    Grain,
    Cave,
    Stand,
    Bamboo,
    Rice,
    Silk,
    Jar,
    Net,
    Sheep,
    Feather,
    Old,
    And,
    Plow,
    Ear,
    Brush,
    Meat,
    Minister,
    OnesSelf,
    Arrive,
    Mortar,
    Tongue,
    Oppose,
    Boat,
    Stopping,
    Color,
    Grass,
    Tiger,
    Insect,
    Blood,
    WalkEnclosure,
    Clothes,
    Cover,
    See,
    Horn,
    Speech,
    Valley,
    Bean,
    Pig,
    Badger,
    Shell,
    Red,
    Run,
    Foot,
    Body,
    Cart,
    Bitter,
    Morning,
    Walk,
    City,
    Wine,
    Distinguish,
    Village,
    Gold,
    Long,
    Gate,
    Mound,
    Slave,
    ShortTailedBird,
    Rain,
    Blue,
    Wrong,
    Face,
    Leather,
    TannedLeather,
    Leek,
    Sound,
    Leaf,
    Wind,
    Fly,
    Eat,
    Head,
    Fragrant,
    Horse,
    Bone,
    Tall,
    Hair,
    Fight,
    SacrificialWine,
    Cauldron,
    Ghost,
    Fish,
    Bird,
    Salt,
    Deer,
    Wheat,
    Hemp,
    Yellow,
    Millet,
    Black,
    Embroidery,
    Frog,
    Tripod,
    Drum,
    Rat,
    Nose,
    Even,
    Tooth,
    Dragon,
    Turtle,
    Flute,
}

impl Into<RadicalGlyph> for KangXi {
    fn into(self) -> RadicalGlyph {
        use KangXi::*;
        match self {
            One => '一'.into(),
            Line => '丨'.into(),
            Dot => '丶'.into(),
            Slash => RadicalGlyph {
                primary: '丿',
                secondary: &['乀', '⺄'],
            },
            Second => RadicalGlyph {
                primary: '乙',
                secondary: &['乚', '乛'],
            },
            Hook => '亅'.into(),
            Two => '二'.into(),
            Lid => '亠'.into(),
            Man => RadicalGlyph {
                primary: '人',
                secondary: &['亻'],
            },
            Son => '儿'.into(),
            Enter => '入'.into(),
            Eight => RadicalGlyph {
                primary: '八',
                secondary: &['丷'],
            },
            Wide => '冂'.into(),
            ClothCover => '冖'.into(),
            Ice => '冫'.into(),
            Table => '几'.into(),
            Receptacle => '凵'.into(),
            Knife => RadicalGlyph {
                primary: '刀',
                secondary: &['刂', '⺈'],
            },
            Power => '力'.into(),
            Wrap => '勹'.into(),
            Spoon => '匕'.into(),
            Box => '匚'.into(),
            Hiding => '匸'.into(),
            Ten => '十'.into(),
            Divination => '卜'.into(),
            Seal => RadicalGlyph {
                primary: '卩',
                secondary: &['㔾'],
            },
            Cliff => '厂'.into(),
            Private => '厶'.into(),
            Again => '又'.into(),
            Mouth => '口'.into(),
            Enclosure => '囗'.into(),
            Earth => '土'.into(),
            Scholar => '士'.into(),
            Go => '夂'.into(),
            GoSlowly => '夊'.into(),
            Evening => '夕'.into(),
            Big => '大'.into(),
            Woman => '女'.into(),
            Child => '子'.into(),
            Roof => '宀'.into(),
            Inch => '寸'.into(),
            Small => RadicalGlyph {
                primary: '小',
                secondary: &['⺌', '⺍'],
            },
            Lame => RadicalGlyph {
                primary: '尢',
                secondary: &['尣'],
            },
            Corpse => '尸'.into(),
            Sprout => '屮'.into(),
            Mountain => '山'.into(),
            River => RadicalGlyph {
                primary: '巛',
                secondary: &['川'],
            },
            Work => '工'.into(),
            Oneself => '己'.into(),
            Turban => '巾'.into(),
            Dry => '干'.into(),
            ShortThread => RadicalGlyph {
                primary: '幺',
                secondary: &['么'],
            },
            DottedCliff => '广'.into(),
            LongStride => '廴'.into(),
            Arch => '廾'.into(),
            Shoot => '弋'.into(),
            Bow => '弓'.into(),
            Snout => RadicalGlyph {
                primary: '彐',
                secondary: &['彑'],
            },
            Bristle => '彡'.into(),
            Step => '彳'.into(),
            Heart => RadicalGlyph {
                primary: '心',
                secondary: &['忄', '⺗'],
            },
            Halberd => '戈'.into(),
            Door => RadicalGlyph {
                primary: '戶',
                secondary: &['户', '戸'],
            },
            Hand => RadicalGlyph {
                primary: '手',
                secondary: &['扌', '龵'],
            },
            Branch => '支'.into(),
            Rap => RadicalGlyph {
                primary: '攴',
                secondary: &['攵'],
            },
            Script => '文'.into(),
            Dipper => '斗'.into(),
            Axe => '斤'.into(),
            Square => '方'.into(),
            Not => RadicalGlyph {
                primary: '无',
                secondary: &['旡'],
            },
            Sun => '日'.into(),
            Say => '曰'.into(),
            Moon => '月'.into(),
            Tree => '木'.into(),
            Lack => '欠'.into(),
            Stop => '止'.into(),
            Death => RadicalGlyph {
                primary: '歹',
                secondary: &['歺'],
            },
            Weapon => '殳'.into(),
            DoNot => RadicalGlyph {
                primary: '毋',
                secondary: &['母'],
            },
            Compare => '比'.into(),
            Fur => '毛'.into(),
            Clan => '氏'.into(),
            Steam => '气'.into(),
            Water => RadicalGlyph {
                primary: '水',
                secondary: &['氵', '氺'],
            },
            Fire => RadicalGlyph {
                primary: '火',
                secondary: &['灬'],
            },
            Claw => RadicalGlyph {
                primary: '爪',
                secondary: &['爫'],
            },
            Father => '父'.into(),
            Trigrams => '爻'.into(),
            SplitWood => RadicalGlyph {
                primary: '爿',
                secondary: &['丬'],
            },
            Slice => '片'.into(),
            Fang => '牙'.into(),
            Cow => RadicalGlyph {
                primary: '牛',
                secondary: &['牜', '⺧'],
            },
            Dog => RadicalGlyph {
                primary: '犬',
                secondary: &['犭'],
            },
            Profound => '玄'.into(),
            Jade => RadicalGlyph {
                primary: '玉',
                secondary: &['王', '玊'],
            },
            Melon => '瓜'.into(),
            Tile => '瓦'.into(),
            Sweet => '甘'.into(),
            Life => '生'.into(),
            Use => '用'.into(),
            Field => '田'.into(),
            BoltOfCloth => RadicalGlyph {
                primary: '疋',
                secondary: &['⺪'],
            },
            Sickness => '疒'.into(),
            Footsteps => '癶'.into(),
            White => '白'.into(),
            Skin => '皮'.into(),
            Dish => '皿'.into(),
            Eye => RadicalGlyph {
                primary: '目',
                secondary: &['⺫'],
            },
            Spear => '矛'.into(),
            Arrow => '矢'.into(),
            Stone => '石'.into(),
            Spirit => RadicalGlyph {
                primary: '示',
                secondary: &['礻'],
            },
            Track => '禸'.into(),
            Grain => '禾'.into(),
            Cave => '穴'.into(),
            Stand => '立'.into(),
            Bamboo => RadicalGlyph {
                primary: '竹',
                secondary: &['⺮'],
            },
            Rice => '米'.into(),
            Silk => RadicalGlyph {
                primary: '糸',
                secondary: &['糹'],
            },
            Jar => '缶'.into(),
            Net => RadicalGlyph {
                primary: '网',
                secondary: &['⺲', '罓', '⺳'],
            },
            Sheep => RadicalGlyph {
                primary: '羊',
                secondary: &['⺶', '⺷'],
            },
            Feather => '羽'.into(),
            Old => RadicalGlyph {
                primary: '老',
                secondary: &['耂'],
            },
            And => '而'.into(),
            Plow => '耒'.into(),
            Ear => '耳'.into(),
            Brush => RadicalGlyph {
                primary: '聿',
                secondary: &['⺺', '⺻'],
            },
            Meat => RadicalGlyph {
                primary: '肉',
                secondary: &['⺼'],
            },
            Minister => '臣'.into(),
            OnesSelf => '自'.into(),
            Arrive => '至'.into(),
            Mortar => '臼'.into(),
            Tongue => '舌'.into(),
            Oppose => '舛'.into(),
            Boat => '舟'.into(),
            Stopping => '艮'.into(),
            Color => '色'.into(),
            Grass => RadicalGlyph {
                primary: '艸',
                secondary: &['⺿'],
            },
            Tiger => '虍'.into(),
            Insect => '虫'.into(),
            Blood => '血'.into(),
            WalkEnclosure => '行'.into(),
            Clothes => '衣'.into(),
            Cover => RadicalGlyph {
                primary: '襾',
                secondary: &['西', '覀'],
            },
            See => '見'.into(),
            Horn => RadicalGlyph {
                primary: '角',
                secondary: &['⻇'],
            },
            Speech => RadicalGlyph {
                primary: '言',
                secondary: &['訁'],
            },
            Valley => '谷'.into(),
            Bean => '豆'.into(),
            Pig => '豕'.into(),
            Badger => '豸'.into(),
            Shell => '貝'.into(),
            Red => '赤'.into(),
            Run => '走'.into(),
            Foot => RadicalGlyph {
                primary: '足',
                secondary: &['⻊'],
            },
            Body => '身'.into(),
            Cart => '車'.into(),
            Bitter => '辛'.into(),
            Morning => '辰'.into(),
            Walk => RadicalGlyph {
                primary: '辵',
                secondary: &['⻌', '⻍', '⻎'],
            },
            City => RadicalGlyph {
                primary: '邑',
                secondary: &['⻏'],
            },
            Wine => '酉'.into(),
            Distinguish => '釆'.into(),
            Village => '里'.into(),
            Gold => RadicalGlyph {
                primary: '金',
                secondary: &['釒'],
            },
            Long => RadicalGlyph {
                primary: '長',
                secondary: &['镸'],
            },
            Gate => '門'.into(),
            Mound => RadicalGlyph {
                primary: '阜',
                secondary: &['⻖'],
            },
            Slave => '隶'.into(),
            ShortTailedBird => '隹'.into(),
            Rain => '雨'.into(),
            Blue => RadicalGlyph {
                primary: '靑',
                secondary: &['青'],
            },
            Wrong => '非'.into(),
            Face => RadicalGlyph {
                primary: '面',
                secondary: &['靣'],
            },
            Leather => '革'.into(),
            TannedLeather => '韋'.into(),
            Leek => '韭'.into(),
            Sound => '音'.into(),
            Leaf => '頁'.into(),
            Wind => '風'.into(),
            Fly => '飛'.into(),
            Eat => RadicalGlyph {
                primary: '食',
                secondary: &['飠'],
            },
            Head => '首'.into(),
            Fragrant => '香'.into(),
            Horse => '馬'.into(),
            Bone => '骨'.into(),
            Tall => RadicalGlyph {
                primary: '高',
                secondary: &['髙'],
            },
            Hair => '髟'.into(),
            Fight => '鬥'.into(),
            SacrificialWine => '鬯'.into(),
            Cauldron => '鬲'.into(),
            Ghost => '鬼'.into(),
            Fish => '魚'.into(),
            Bird => '鳥'.into(),
            Salt => '鹵'.into(),
            Deer => '鹿'.into(),
            Wheat => '麥'.into(),
            Hemp => '麻'.into(),
            Yellow => '黃'.into(),
            Millet => '黍'.into(),
            Black => '黑'.into(),
            Embroidery => '黹'.into(),
            Frog => '黽'.into(),
            Tripod => '鼎'.into(),
            Drum => '鼓'.into(),
            Rat => '鼠'.into(),
            Nose => '鼻'.into(),
            Even => RadicalGlyph {
                primary: '齊',
                secondary: &['斉'],
            },
            Tooth => '齒'.into(),
            Dragon => '龍'.into(),
            Turtle => '龜'.into(),
            Flute => '龠'.into(),
        }
    }
}

pub struct RadicalGlyph {
    pub primary: char,
    pub secondary: &'static [char],
}

impl From<char> for RadicalGlyph {
    fn from(c: char) -> Self {
        Self {
            primary: c,
            secondary: &[],
        }
    }
}
